### ISSUE TITLE
Services API

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#146]
Within Ghost-CLI there are currently several "concepts":
- commands - full commands that have arguments and options 
  - e.g. `ghost install`, `ghost start` etc.
- tasks - self-contained functions reused between commands
- process managers - ways of running ghost

These concepts work for most of the usages of the CLI, however there are several things the CLI still needs to do that don't fit into a particular category. The main ones (listed in #64) are setting up nginx and ssl. Both of these things are not super complex, but still need things done at specific times during various commands.

So, to encapsulate & abstract some of the operations and setup of nginx and ssl (and whatever else may come or be needed), there is going to be an additional concept added to the CLI: **Services**

---
## Design

- Hooks
  - Services should be able to hook into various CLI commands to do various things
    - example: during `ghost setup` an nginx/ssl service should be able to set up various config files
- Commands
  - while adding commands to the root of `ghost` might be tricky due to the need to resolve external commands, so we should potentially add a `ghost service` command which could handle installation of external services  (`ghost service install`) as well as any custom commands that a provider might define
    - example: `ghost service ssl` for an ssl provider might call the letsencrypt renew function. This could be set as a cron task to run every so often.

---
## Resolution

Because services would be installed globally, there needs to be a resolution process that is able to reliably find all of the globally installed services and load them. This is not a trivial process - Yeoman accomplishes it using a sort of "guess and check" method (see [this file](https://github.com/yeoman/environment/blob/master/lib/resolver.js) for how it's done). With the introduction of Yarn, however, there can be now be multiple places that globally installed modules are _actually_ installed. (yarn installs all of its global modules in a different location than that of npm by default)

So, here's the thought for resolution: `ghost service install` would install a service globally using yarn. Instead of installing it to yarn's default global node_modules folder, it would instead place it inside a folder in the user's HOME directory, as well as adding the service to a config file in the same folder. That way, there is one place that all the providers are installed, making the resolution process much less of a guess, and therefore (hopefully) much faster.

This resolution process would be extended to process managers as well, in a sense making them a special type of service, in a sense.

---

## TODOs

- [x] Short-term
  - [x] build out initial api in the CLI itself
  - [x] Add nginx and ssl service so that they are present in every install of the CLI (pr - #159)
- [ ] Long-term
  - [ ] extract base service into a separate NPM module
  - [ ] move nginx and ssl service into separate npm modules - still required by Ghost-CLI though
  - [ ] build out resolution process
