### ISSUE TITLE
Acme.sh certificate renewal is not complete

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#495]
I'm having problems with sites going offline with certificate errors. Acme.sh is correctly renewing the certificates, but nginx must be restarted afterwards, and I don't think that has been configured.

I'm not sure why we haven't had a tonne more reports of this!

Refs: 

- https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc
- https://www.rmedgar.com/blog/using-acme-sh-with-nginx

**Update from @ErisDS 23rd Oct:**

We're starting to see more people affected by this. To aid search-ability this manifests itself as `NET::ERR_CERT_DATE_INVALID` errors on your site.

The certificate _has_ renewed, but nginx needs to be restarted to pick up the new certs:

The solution is to run `sudo systemctl restart nginx` on your box.

--- 

## Task list 

(Taken from my comment below)

- [x] 1. Build out the new version
- [ ] 2. Write the documentation for how to manually migrate your site to the new version
     - My expectation is the simple version would be "run `ghost setup:ssl`, then delete X files" or similar, and then there'd be an extended version explaining the exact steps for anyone with a customised system.
- [x] 3. Release the new version as a minor?

At this point, all new sites are safe, all old ones _can_ migrate.

- [ ] 4. Write a check that can determine if a blog is using the old ssl setup, make it as robust and simple as possible. E.g. use `fs.exists`.
- [ ] 5. Add a message to as many places as possible shouting about the need to update, linking to the docs.
- [ ] 6. Release as a patch update

At this point, all old blogs will learn about the need to migrate. They will be able but it's not easy.

- [ ] 7. Add a new command: `ghost migrate:ssl` or something equally relatively sensible and future-proof.
- [ ] 8. Make that command do the necessary migration steps 
      - e.g. it runs `ghost setup:ssl` and then deletes the old files, or maybe does a more advanced set of steps to be more compatible?
- [ ] 9. Update the docs with the shiny new command
- [ ] 10. _Maybe_ update the messages every where with the new command?

At this point, all old blogs have an easy way to migrate.

- [ ] 11. Deal with any fall out, e.g. bugs in the check, or improvements to the migrate command to ensure these are robust.
- [ ] 12. Implement a system to auto-migrate

**Comment by benaubin** [comment]
See the `--reloadcmd` option for acme.sh: https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc

**Comment by acburdine** [comment]
So yeah, this bug is pretty bad. I apologize for not catching this one sooner.

After doing some research - I've discovered an unfortunate reality: _We need sudo permissions to restart nginx._

There are several different commands that can be run to reload nginx that I found. They are:
- `service reload nginx` / `systemctl nginx reload` (for our intent they're essentially the same)
- `nginx -s reload`
- `kill -HUP <nginx process id>`

None of the above commands works without sudo permissions, specifically because it requires messing with the nginx process, which the user that runs the acme script won't be able to do without sudo. Also with sudo access, it makes the cron script difficult because it requires a password to be typed in.

As such, there are two different solutions that I can see:

1. Run acme as the root user & set it up as such.

This solution is probably the easier one to implement for _new_ installations, however it would be a bit of a nightmare for updating existing Ghost-CLI installations. It's also potentially more of a security issue.

2. Add a line to the sudoers file manually that allows sudo to be executed without a password ONLY for the nginx reload command.

This would potentially be a lot easier to migrate older installations to - and would alleviate the problem of running things as root. However, it would require modification of the sudoers file which I bet most people might be a bit fearful of. We could do it automatically, but it's still a bit scary.

This _is_ just my results from the research I've done into this, the reason I'm posting it is I want to make sure there aren't any other ways of accomplishing this that don't involve major changes with sudo.

@sebgie I'm gonna ping you on this one as well, have any other ideas?

**Comment by acburdine** [comment]
After a conversation with @sebgie on Slack, we've decided to go with option 1.

Acme.sh has an option to set the certs up in a location other than the home directory - for new installs it will install all the certs to `/etc/letsencrypt` rather than `~/.acme.sh`. We will also run acme.sh as root, which fixes any permissions issues we have with nginx.

This will require building out some of the abilities to migrate installation structures, as moving existing ssl setups with Ghost-CLI will require a bit of extra work.

**Comment by ErisDS** [comment]
> This will require building out some of the abilities to migrate installation structures, as moving existing ssl setups with Ghost-CLI will require a bit of extra work.

I totally get that we need to do this sometime, and that it's not a small amount of work. 

For now, how does this approach sound:

- [ ] 1. Build out the new version
- [ ] 2. Write the documentation for how to manually migrate your site to the new version
     - My expectation is the simple version would be "run `ghost setup:ssl`, then delete X files" or similar, and then there'd be an extended version explaining the exact steps for anyone with a customised system.
- [ ] 3. Release the new version as a minor?

At this point, all new sites are safe, all old ones _can_ migrate.

- [ ] 4. Write a check that can determine if a blog is using the old ssl setup, make it as robust and simple as possible. E.g. use `fs.exists`.
- [ ] 5. Add a message to as many places as possible shouting about the need to update, linking to the docs.
- [ ] 6. Release as a patch update

At this point, all old blogs will learn about the need to migrate. They will be able but it's not easy.

- [ ] 7. Add a new command: `ghost migrate:ssl` or something equally relatively sensible and future-proof.
- [ ] 8. Make that command do the necessary migration steps 
      - e.g. it runs `ghost setup:ssl` and then deletes the old files, or maybe does a more advanced set of steps to be more compatible?
- [ ] 9. Update the docs with the shiny new command
- [ ] 10. _Maybe_ update the messages every where with the new command?

At this point, all old blogs have an easy way to migrate.

- [ ] 11. Deal with any fall out, e.g. bugs in the check, or improvements to the migrate command to ensure these are robust.
- [ ] 12. Implement a system to auto-migrate 

------

If it's possible, joining 1-6 together would be _ideal_, but I'd rather ship something that _can_ be done manually as soon as physically possible, than delay at all on making migrations easier/not manual.

Also - if you can provide a bullet-point list of commands that result in a migration, then I can write the docs 😊

**Comment by ErisDS** [comment]
I've updated the top issue to make it more searchable. I have also added a section to the troubleshooting guide: https://docs.ghost.org/v1/docs/troubleshooting#section-net-err_cert_date_invalid, and a red callout on the install page: https://docs.ghost.org/v1/docs/install.

Hopefully this will help anyone who runs into this issue (had 2 today in #help on https://slack.ghost.org) find the answer quickly. 

Let me know if there's anywhere else I should update or any further docs I can write.

**Comment by benaubin** [comment]
nice!

**Comment by ErisDS** [comment]
@acburdine should we maybe move the list of tasks out of this issue now and into a new one?

**Comment by acburdine** [comment]
Docs have been updated, blog post published with more information about this bug & how to fix, so this is (finally 😛) done.

**Comment by maximusk** [comment]
Is there a `systemd` service that checks for the certificate validity and updates it?

**Comment by maximusk** [comment]
@vikaspotluri123 , got it, thanks a lot for the fast reply. ghost-cli uses `systemd` to setup ghost service, I'm wondering why isn't it using `systemd` timers to run the acme renewal script?

**Comment by maximusk** [comment]
@vikaspotluri123 , got it, thanks a lot for the fast reply. ghost-cli uses systemd to setup ghost service, I'm wondering why isn't it using systemd timers to run the acme renewal script?

**Comment by vikaspotluri123** [comment]
@maximusk could we move this discussion to the [forum topic](https://forum.ghost.org/t/is-there-a-systemd-service-that-checks-for-a-certificate-validity-and-updates-it/7194/2)? Thanks!
