### ISSUE TITLE
Road to 💯 - Tests

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Ghost-CLI#541]
Here's an abstract list of things the cli does, and how well they're tested (via unit tests)

### Extensions: 
- [x] MySQL
- [x] Nginx (#523, #542)
- [x] Systemd (#544)

### Commands: 
- [x] buster
- [x] install
- [x] log (#545)
- [x] ls
- [x] migrate
- [x] restart
- [x] run
- [x] setup (#559)
- [x] start (#560)
- [x] stop (#582)
- [x] uninstall (#585)
- [x] update 
- [x] version

### Tasks:
- [x] ensure-structure
- [x] linux
- [x] migrate
- [ ] yarn-install (#586)

### Utils:
- [x] config
- [x] find-extensions
- [x] needed-migrations
- [x] resolve-version
- [x] update-check
- [x] use-ghost-user
- [x] version-from-zip
- [ ] yarn (#586)

### Misc:
- [x] Remove spec files from coverage reports (#543)
- [x] bootstrap

**Comment by AileenCGN** [comment]
When I run the tests locally, there's always one test that fails, but it's fine in Travis:

 ```
 1) Unit: Extensions > Nginx
       migrations hook
         [before 1.2.0]
           Doesn't skip if acme.sh exists:

      AssertionError: expected true to be false
      + expected - actual

      -true
      +false

      at Context.<anonymous> (extensions/nginx/test/extension-spec.js:73:51)
```

**Comment by vikaspotluri123** [comment]
@AileenCGN I _think_ it's because we haven't stubbed `os`; I'm thinking `os.platform() !== linux` evaluates to `true` locally for you.

I haven't hit this because I test with [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)  which is technically a linux platform
