### ISSUE TITLE
EPIC: Support HTTPS-only for Ghost admin

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#864]
This is an epic, as it collects together many sub issues that pave the way towards a breaking change we're intending to make in Ghost 3.0:

We are intending to change the rules around URL and protocols to:

1. If config.url has http configured, the frontend will serve over http ONLY
2. If config.url has https configured, the frontend will serve over https ONLY
3. Ghost admin MUST be served over https in production mode, therefore either config.admin, or config.url MUST be https.

The expectation is that ghost admin (and the API) will error if HTTPS is not available, until such time as it is. 

We will also strongly recommend that the frontend URL is HTTPS

To get there in terms of support in the CLI, there are some quick wins and bigger features to build.

Now:
- [ ] Introduce warning messages for production sites not running HTTPS: https://github.com/TryGhost/Ghost-CLI/issues/863

Next:
- [ ] Add `ghost url` command: https://github.com/TryGhost/Ghost-CLI/issues/224
- [ ] Make sure that HTTP redirects to HTTPS: https://github.com/TryGhost/Ghost-CLI/issues/826
- [ ] Improvements to SSL error handling: https://github.com/TryGhost/Ghost-CLI/issues/832

For 3.0
- [ ] Change to automatically assuming HTTPS when a URL is entered in config for non-local installs

**Comment by ErisDS** [comment]
This work is not longer planned
